### ISSUE TITLE
Become GitHub partner organization to receive verified badge on the Marketplace

### ISSUE THREAD

**Issue by shyamkumarm-ctct** [android-actions/setup-android#415]
I'm getting the following error after triggering the workflow: runs on [self-hosted]

Error: .github#L1 android-actions/setup-android@v3 is not allowed to be used in repo/products. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace

**Comment by ViliusSutkus89** [comment]
I've published v3.1.0 to GitHub Marketplace. `android-actions/setup-android@v3` should work now for you. Let me know if it doesn't

**Comment by shyamkumarm-ctct** [comment]
Thank you. I have attached the verified JDK for your reference. In the same way, the issue we are having is that your Android SDK actions have not been verified by the Github Marketplace. Is it possible to rectify this?

![image](https://github.com/android-actions/setup-android/assets/132995150/05802cd1-3b91-4787-9730-2aae4bbbb9f6)

**Comment by ViliusSutkus89** [comment]
Ahh, yes, I see. We need to become a "partner organization" to get the check mark. Unsure how to proceed with it, will look into it.
![image](https://github.com/android-actions/setup-android/assets/812793/43b3b015-4fe7-44c2-984b-85f360d2f1ea)

 In the meantime, wording from your original error implies that you are allowed to use regular unverified actions from your own organization, so just fork this repo. Keep in mind that you will not be getting updates automatically and will have to occasionally pull updates by yourself

```yaml
steps:
- uses: actions/checkout@v4

- name: Set up JDK 17
  uses: actions/setup-java@v3
  with:
    java-version: '17'
    distribution: 'temurin'

- name: Setup Android SDK
  uses: shyamkumarm-ctct/setup-android@v3

- name: Build SampleApplication
  run: ./gradlew --no-daemon build
```
