### ISSUE TITLE
How to start an emulator for android app Espresso UI Testing in Windows environment?

### ISSUE THREAD

**Issue by yong2khoo-lm** [android-actions/setup-android#483]
Would like to ask, as titled, 
How to start an emulator for android app Espresso UI Testing in Windows environment?

Below is my yml. 

```yml
name: Run Espresso UI Testing

on:
  workflow_dispatch:
  push:
    branches:
      - TestGithubActionEspresso
jobs:
  run-espresso:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew


      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'
          components: platform-tools, emulator

      - name: Install system image for emulator
        run: |
          sdkmanager.bat "system-images;android-34;google_apis;x86_64"
          sdkmanager.bat --licenses

      - name: Create and start the emulator
        run: |
          emulator.exe -avd test -no-window -no-audio -no-boot-anim
          timeout /t 120
          adb wait-for-device
          adb shell input keyevent 82
```

So far it works great till the last part
`emulator.exe -avd test -no-window -no-audio -no-boot-anim`
With error "The term emulator.exe is not recognized ..."
![image](https://github.com/user-attachments/assets/a57c1614-a499-4ef2-9cf4-f41de39021f6)

What did i miss?
Thanks in advance.
