### ISSUE TITLE
Build with ndk

### ISSUE THREAD

**Issue by SimonIT** [android-actions/setup-android#67]
I tried to setup a libGDX application for building.

On the first build is the wrong ndk version installed.

https://github.com/SimonIT/CollapseTheGame/runs/1460452130

After specifying the installed ndk version in the build.gradle the following error appears:

https://github.com/SimonIT/CollapseTheGame/runs/1460505051

(More details: https://github.com/SimonIT/CollapseTheGame/runs/1465844104)

**Comment by ViliusSutkus89** [comment]
@SimonIT , this is available since setup-android@v2.0.3 , try it out.

```yaml
- name: Setup Android SDK
  uses: android-actions/setup-android@v2

- name: Install NDK
  run: sdkmanager "ndk;22.0.7026061"
```
